remote_theme: pages-themes/cayman@v0.2.0
base_url: "/"
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

title: "OzFlySIM"

github:
  is_project_page: false

kramdown:
  smart_quotes:
  hard_wrap: true